import { privateKeyToAccount } from "viem/accounts";

const tg = window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const params = new URL(location.href).searchParams, action = params.get("action") || "wallet", jobId = params.get("job") || "";
const iterations = 600_000, utf8 = new TextEncoder(), databaseName = "zktx-trusted-device-v1";
const encode = (bytes) => btoa(String.fromCharCode(...bytes));
const decode = (value) => Uint8Array.from(atob(value), (character) => character.charCodeAt(0));
const status = (text) => document.querySelector("#status").textContent = text;
let activeAccount;
async function db(){return new Promise((resolve,reject)=>{const request=indexedDB.open(databaseName,1);request.onupgradeneeded=()=>request.result.createObjectStore("keys");request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function storedKey(address){const database=await db();return new Promise((resolve,reject)=>{const request=database.transaction("keys","readonly").objectStore("keys").get(address.toLowerCase());request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);}).finally(()=>database.close());}
async function saveKey(address,key){const database=await db();await new Promise((resolve,reject)=>{const request=database.transaction("keys","readwrite").objectStore("keys").put(key,address.toLowerCase());request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);}).finally(()=>database.close());}
async function derive(passphrase,vault){if(passphrase.length<12)throw new Error("Use a recovery passphrase with at least 12 characters");const material=await crypto.subtle.importKey("raw",utf8.encode(passphrase),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:decode(vault.salt),iterations:vault.kdfIterations,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);}
async function encrypt(secret,passphrase){const normalized=secret.startsWith("0x")?secret:`0x${secret}`;if(!/^0x[0-9a-fA-F]{64}$/.test(normalized))throw new Error("Enter a valid EVM private key");const account=privateKeyToAccount(normalized),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(passphrase,{salt:encode(salt),kdfIterations:iterations});const ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv,additionalData:utf8.encode(`ZKTX:${account.address}:1`)},key,utf8.encode(normalized)));return{account,key,envelope:{version:1,address:account.address,ciphertext:encode(ciphertext),iv:encode(iv),salt:encode(salt),kdf:"PBKDF2-SHA256",kdfIterations:iterations}};}
async function decryptVault(vault,key){const clear=await crypto.subtle.decrypt({name:"AES-GCM",iv:decode(vault.iv),additionalData:utf8.encode(`ZKTX:${vault.address}:1`)},key,decode(vault.ciphertext));const account=privateKeyToAccount(new TextDecoder().decode(clear));if(account.address.toLowerCase()!==vault.address.toLowerCase())throw new Error("Vault address mismatch");return account;}
async function api(path,options={}){if(!tg?.initData)throw new Error("Open this page from the ZKTX Telegram bot");const response=await fetch(`/telegram-api${path}`,{...options,headers:{"content-type":"application/json","x-telegram-init-data":tg.initData,...options.headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Secure wallet request failed");return payload;}
async function ready(account){activeAccount=account;document.querySelector("#wallet").hidden=false;document.querySelector("#address").textContent=account.address;if(action==="authorize"){const {message,job}=await api(`/api/v1/jobs/${encodeURIComponent(jobId)}`);document.querySelector("#review").hidden=false;document.querySelector("#summary").textContent=message;const button=document.querySelector("#authorize");button.hidden=false;button.onclick=async()=>{button.disabled=true;try{status("Signing locally…");const response=await api(`/api/v1/jobs/${encodeURIComponent(job.id)}/authorize`,{method:"POST",body:JSON.stringify({signature:await activeAccount.signMessage({message})})});status(response.status==="authorized_ready"?"Authorized. Return to Telegram and continue to proof generation.":"Authorized. Execution will remain unavailable until the relayer and PONS keeper are online.");}catch(error){status(error.message||"Authorization failed");button.disabled=false;}};}status("Wallet unlocked on this trusted device.");}
async function bootstrap(){if(action==="import"){document.querySelector("#import").hidden=false;status("Import and encrypt your wallet locally.");return;}try{const {vault}=await api("/api/v1/vault"),key=await storedKey(vault.address);if(!key)throw new Error();await ready(await decryptVault(vault,key));}catch{document.querySelector("#unlock").hidden=false;status("Enter the recovery passphrase to unlock this device.");}}
document.querySelector("#import").onsubmit=async(event)=>{event.preventDefault();const secret=document.querySelector("#private-key"),passphrase=document.querySelector("#passphrase");try{status("Encrypting locally…");const result=await encrypt(secret.value.trim(),passphrase.value);secret.value="";passphrase.value="";await api("/api/v1/vault",{method:"PUT",body:JSON.stringify(result.envelope)});await saveKey(result.account.address,result.key);status(`Wallet ${result.account.address.slice(0,8)}…${result.account.address.slice(-6)} imported on this trusted device.`);}catch(error){secret.value="";passphrase.value="";status(error.message||"Import failed");}};
document.querySelector("#unlock").onsubmit=async(event)=>{event.preventDefault();const passphrase=document.querySelector("#unlock-passphrase");try{const {vault}=await api("/api/v1/vault"),key=await derive(passphrase.value,vault);passphrase.value="";const account=await decryptVault(vault,key);await saveKey(vault.address,key);document.querySelector("#unlock").hidden=true;await ready(account);}catch{passphrase.value="";status("Wallet unlock failed.");}};
void bootstrap();
